### ISSUE TITLE
Installation issue due to malformatted version

### ISSUE THREAD

**Issue by gcmalloc** [Orange-OpenSource/bagpipe-bgp#18]
I tried installing bagpipe-bgp, but it didn't work due to the version number being malformated.

```
error in setup command: Error parsing /bagpipe/setup.cfg: ValueError: Unknown remainder ['pre'] in '1.81pre'
```

For the whole stack trace
```
ERROR:root:Error parsing
Traceback (most recent call last):
  File "/bagpipe/.eggs/pbr-1.10.0-py2.7.egg/pbr/core.py", line 111, in pbr
    attrs = util.cfg_to_args(path, dist.script_args)
  File "/bagpipe/.eggs/pbr-1.10.0-py2.7.egg/pbr/util.py", line 246, in cfg_to_args
    pbr.hooks.setup_hook(config)
  File "/bagpipe/.eggs/pbr-1.10.0-py2.7.egg/pbr/hooks/__init__.py", line 25, in setup_hook
    metadata_config.run()
  File "/bagpipe/.eggs/pbr-1.10.0-py2.7.egg/pbr/hooks/base.py", line 27, in run
    self.hook()
  File "/bagpipe/.eggs/pbr-1.10.0-py2.7.egg/pbr/hooks/metadata.py", line 26, in hook
    self.config['name'], self.config.get('version', None))
  File "/bagpipe/.eggs/pbr-1.10.0-py2.7.egg/pbr/packaging.py", line 716, in get_version
    version = _get_version_from_git(pre_version)
  File "/bagpipe/.eggs/pbr-1.10.0-py2.7.egg/pbr/packaging.py", line 652, in _get_version_from_git
    pre_version)
  File "/bagpipe/.eggs/pbr-1.10.0-py2.7.egg/pbr/version.py", line 147, in from_pip_string
    return klass._from_pip_string_unsafe(version_string)
  File "/bagpipe/.eggs/pbr-1.10.0-py2.7.egg/pbr/version.py", line 223, in _from_pip_string_unsafe
    % (remainder, version_string))
ValueError: Unknown remainder ['pre'] in '1.81pre'
error in setup command: Error parsing /bagpipe/setup.cfg: ValueError: Unknown remainder ['pre'] in '1.81pre'
```

**Comment by tmmorin** [comment]
Thanks for reporting that!
